### ISSUE TITLE
[Enhancement]: Change Add to "*arr +" button to "Request"

### ISSUE THREAD

**Issue by gerryflux** [aleksilassila/reiverr#116]
This app has something great going for it, and I hope it does succeed.
I would like to request if it could be possible to change the "Add to *arr +" button to just read "Request".
![image](https://github.com/aleksilassila/reiverr/assets/52464120/800c5267-42db-4223-8385-954b127b08f9)
At the back-end we know if it's a movie or a show, it shall be sent to Radarr and and Sonarr, respectively.
So, the end user, this detail is insignificant and might be confusing to them.

**Comment by aleksilassila** [comment]
I agree that having it behave as you described would be optimal, but the reason it is like this is that behind the scenes before you can ask radarr or sonarr to show the release files for a movie or show, you have to tell radarr or sonarr to "add" the movie or show first. Do you recon it would be best if this would be done automatically when you press the request button?

**Comment by Phelra** [comment]
Personally, I also think it would be a good idea to combine the "request a movie" and "add a *darr" buttons into a single button.

**Comment by aleksilassila** [comment]
This is addressed as much as it can be in the 2.0 release in a couple of days. I can't remove the add to radarr/sonarr part as the item has to be added to the services to get the releases from their api, but you won't need to click it twice anymore.
