### ISSUE TITLE
[Feature Request] Emby Support

### ISSUE THREAD

**Issue by Amateur-God** [aleksilassila/reiverr#118]
Would it be possible to add support for emby

**Comment by Starstrike** [comment]
@Amateur-God I see you closed this as completed, but what's the answer? lol. I'm kinda watching this project but no point if Emby won't be supported.

**Comment by Amateur-God** [comment]
I have no idea, I closed it as I realised that I had already made the same issue 9 months ago and then forgot all about it and didn't want to duplicate my own issues
