### ISSUE TITLE
Maybe Bug?

### ISSUE THREAD

**Issue by Amateur-God** [aleksilassila/reiverr#119]
i can seem to create a profile or password, if i click on the user icon nothing happens 
![image](https://github.com/aleksilassila/reiverr/assets/68581288/2d311214-2ac9-448f-8b01-fae3e3b13318)

which means im unable to create a user account or set a password to access it

**Comment by aleksilassila** [comment]
This is actually just because the feature is implemented still and the button does nothing. User accounts will be added in the 2.0 release
