### ISSUE TITLE
Hardcoded UserID for Jellyfin

### ISSUE THREAD

**Issue by karbowiak** [aleksilassila/reiverr#40]
Hi there, there seems to be a b0rk here https://github.com/aleksilassila/reiverr/blob/master/src/lib/stores/settings.store.ts#L49

I am a dolt at TypeScript, otherwise i'd make a pull request making it set it via ENV 😅 

(I guess it goes for all the variables in that settings file actually)

**Comment by aleksilassila** [comment]
Good catch! I hotfixed this in v0.3.0, it will use the first jellyfin user that is available until I get a chance to do a proper fix next week.
