### ISSUE TITLE
Bug  - JSON Parsing

### ISSUE THREAD

**Issue by elythh** [aleksilassila/reiverr#43]
Hello, I just installed reiverr but I'm not able to get it to work. 
I can see the requests at Jellyfin/Sonarr/Radarr working fine but nothing shows up in the Source/Library tabs.
The only hint I have is from the browser console.
```
Uncaught (in promise) SyntaxError: Unexpected token 'E', "Error proc"... is not valid JSON
```
Is it a known issue ? I'm trying to find more clues about what"s causing the issue but no logs are showing except that

**Comment by elythh** [comment]
Some more context. This is when loading the Sources page
![image](https://github.com/aleksilassila/reiverr/assets/50964650/6cb5d42c-076a-43fc-8437-1a27a1f544d6)

**Comment by fredrikburmester** [comment]
I think this might be related to the error inte the logs:
```
reiverr  | Error: Not found: /genres/western.jpg
reiverr  |     at resolve (file:///usr/src/app/build/server/index.js:3925:18)
reiverr  |     at resolve (file:///usr/src/app/build/server/index.js:3800:34)
reiverr  |     at #options.hooks.handle (file:///usr/src/app/build/server/index.js:3970:61)
reiverr  |     at respond (file:///usr/src/app/build/server/index.js:3798:43)
```

**Comment by elythh** [comment]
0.3.0 seem to fix the issue, I'll close for now
![image](https://github.com/aleksilassila/reiverr/assets/50964650/e8fbafb3-dd76-4ef8-ba27-f6e000c95f21)
