### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by skhalid93** [aleksilassila/reiverr#45]
Will this have any support outside of docker? As of this moment only see one installation method which is through docker.

**Comment by TomFaulkner** [comment]
I'm not a contributor here, but you could follow the commands from the Dockerfile to install it locally on Linux.

**Comment by skhalid93** [comment]
> 

Just did. 


git clone https://github.com/aleksilassila/reiverr.git
cd reiverr
pnpm install
pnpm run build
pnpm run dev



Create .env file:

# Fill in the blanks and change the base URLs to match your setup.

PUBLIC_RADARR_API_KEY=yourapikeyhere
PUBLIC_RADARR_BASE_URL=http://127.0.0.1:7878

PUBLIC_SONARR_API_KEY=yourapikeyhere
PUBLIC_SONARR_BASE_URL=http://127.0.0.1:8989

PUBLIC_JELLYFIN_API_KEY=yourapikeyhere
PUBLIC_JELLYFIN_URL=http://127.0.0.1:8096

**Comment by aleksilassila** [comment]
That should work, you could also clone the project and remove the amd64 platform flag from the Dockerfile to build for your platform from source. If anyone knows a proper solution to supporting multiple platforms with a single image, let me know

**Comment by Klubas** [comment]
@aleksilassila it's possible, just a bit tricky https://docs.docker.com/build/building/multi-platform/

**Comment by fabricionaweb** [comment]
@skhalid93 Does it make sense to suggest `npm` instead of `pnpm`? Im saying it because the project is using `npm` and it have the `package-lock.json`.

@aleksilassila Do you think it would be handy have it at README as well?

**Comment by aleksilassila** [comment]
Sure, I can add it to the README.

**Comment by fabricionaweb** [comment]
> Sure, I can add it to the README.

Do you mind if I contribuite to this one? I have few suggestions :)

**Comment by aleksilassila** [comment]
Sure, go ahead.
