### ISSUE TITLE
Jellyfin movies all marked as Unavailable

### ISSUE THREAD

**Issue by HelamanWarrior** [aleksilassila/reiverr#67]
After updating to v0.4.0, I noticed that all of the movies in my library were marked `Unavailable`. Just yesterday they were all marked as `Available`. I also noticed in the movie page the "Open in Jellyfin" button is grayed out.

I checked the logs in Reiverr, Jellyfin, and Radarr, but I didn't see anything related to this issue.

If I need to take further steps to debug this issue, let me know, I would love to help

**Comment by aleksilassila** [comment]
Were you able to play the items before 0.4.0? Also is your jellyfin api keys & urls correct in your environment? Previously items were marked as available if radarr or sonarr said they had files, now they are marked available only if they have been imported to jellyfin. 

Could you also see if you have any errors in your browsers console? (F12 or inspect elements > console)

**Comment by HelamanWarrior** [comment]
Ohhh this was totally my bad. Sorry about that, when I put in the reverse proxied url `https://jellyfin.example.com/` I left a trailing slash. I was able to fix it by removing the trailing slash like this `https://jellyfin.example.com`.

Everything works now, thanks for the help.
