### ISSUE TITLE
Add Option of Multiple Root Folder for Sonarr, Radarr

### ISSUE THREAD

**Issue by aaemon** [aleksilassila/reiverr#84]
This feature is necessary for users who like to maintain multiple root folders for different categories.

**Comment by Auxtal** [comment]
+1

**Comment by SkalCore** [comment]
+1

**Comment by aleksilassila** [comment]
If I understand correctly this should be addressed in the 2.0 release as you'll have the change to change the root folder each time you add an item to radarr / sonarr. Reopen / comment if I'm mistaken
