### ISSUE TITLE
Environment Variables no longer used

### ISSUE THREAD

**Issue by TomFaulkner** [aleksilassila/reiverr#85]
The new integrations setup page is nice, but I would prefer to configure the app through environment variables. Can you change to prefer environment variables over the database? It's easier to keep my docker-compose file in git rather than have to backup a database.

**Comment by chris-kruining** [comment]
same here, I run it in a container on nixos. So I too would love to have this work declaritively. Right now I loose all my integration config after reboot

**Comment by aleksilassila** [comment]
With the introduction of multiple users in 2.0, I don't think this is feasible anymore, especially when the project is committed to using a database now.
